task: detection

num_classes: 1
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: D:/datasets/NpsDrones_v20221030/train
    ann_file: D:/datasets/NpsDrones_v20221030/annotations/COCO_train_w_id_20221027.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: D:/datasets/NpsDrones_v20221030/train
    ann_file: D:/datasets/NpsDrones_v20221030/annotations/COCO_val_w_id_20221027.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 4
  num_workers: 2
  drop_last: False